### ISSUE TITLE
Can this plugin be enabled only for Android/AndroidTV platform?

### ISSUE THREAD

**Issue by dblachut-adb** [aeirola/react-native-svg-asset-plugin#20]
Hi, I was wondering if this plugin could be enabled only in case of Android/AndroidTV platform? Maybe this can be done in `metro.config.js` file?

I am using this plugin because SVG assets are not supported directly in Android, but I wouldn't like to change how SVGs are used on other platforms. 

Any help would be appreciated.

**Comment by aeirola** [comment]
The plugin itself doesn't support any platform specific configuration, and I don't think React Native nor the Metro bundler supports platform specific plugins.

What is your use case for only enabling the plugin on certain platforms? How do you expect the `require('image.svg')` to behave in situations where the plugin has been disabled? As far as I know, at least none of the official react native platforms support SVG by themselves.

**Comment by aeirola** [comment]
Hmm, that sounds like a bit of a strange use case. I don't really see the point in using different image rendering methods on different platforms. I'd say the effort would be better spent on fixing the issues in the react-native-svg-from-uri package instead.

Alternatively, just use something else based on react-native-svg runtime rendering instead. https://github.com/kristerkari/react-native-svg-transformer looks handy.

**Comment by dblachut-adb** [comment]
Sure, I will give it a try although from initial research it seems to people are reporting some problems with it. Thanks for reaching out.
