### ISSUE TITLE
Colons are not allowed in file names on Windows

### ISSUE THREAD

**Issue by zs-doron** [aeirola/react-native-svg-asset-plugin#27]
Using a colon in the file names created here:
`const outputName = `${assetData.name}:${assetData.hash}`;`
causes issues on Windows, the PNG files are not created (instead you get empty files in the cache folder).

**Comment by aeirola** [comment]
Very true, and quite unnecessary by me to use a colon as a field seoarator in the filename. I guess it could just as well be changed to a dash without too much harm.

Do you want to make a PR to fix the issue?

I guess it might also be wise for me to setup the CI to run on windows as well.

**Comment by zs-doron** [comment]
Thanks for your fast feedback (and this usefull library), fix in PR #28.
I guess it should make me think that I obviously am the first developer using this library on Windows.

**Comment by aeirola** [comment]
Support for windows was released in version 0.3.0. Sorry for the wait, but didn't want to publish before I got the windows CI set up, as I don't have a windows development machine to ensure windows support to be properly working in the future as well.
