### ISSUE TITLE
Is it possible to change the color?

### ISSUE THREAD

**Issue by manoelramos** [aeirola/react-native-svg-asset-plugin#34]
I am using the Image component to display svg, it is working normally, however I wanted to set the color, but I can't.

**Comment by aeirola** [comment]
The library itself doesn't make any changes to the image colors, it just converts the SVG files to PNG files, which are passed to react native.

To change the color of the images, you would either need to change the SVG file, or alternatively use the [`tintColor`](https://facebook.github.io/react-native/docs/image-style-props#tintcolor) style prop of the react native Image component.
