### ISSUE TITLE
is it possible to use with react-native-fastimage? 

### ISSUE THREAD

**Issue by ssilverr** [aeirola/react-native-svg-asset-plugin#35]
React native fastimage is pretty much superior to the built in image component.

**Comment by aeirola** [comment]
This plugin is for converting local images from SVG to PNG during compile time before they are packaged into the application package. `FastImage` is a library to improve the performance of images fetched over the network. Thus I don't really how the projects would be used together.

If you want to convert SVG images to PNGs on the server side as they are fetched by the application, there are probably multiple different libraries available for that.

**Comment by ssilverr** [comment]
`FastImage` is can be used to change `tintcolor`, so you can use .png assests as icons, no need for an Icon library, or several versions of the same .png. So it's not a strictly for fetching images.

**Comment by aeirola** [comment]
Oh, okay. Then I guess it should work just as well with the `FastImage` component as well. Although the React Native `Image` component does support the `tintColor` [style prop](https://facebook.github.io/react-native/docs/image#style) as well, so not really sure what the benefit of using `FastImage` would be.

**Comment by aeirola** [comment]
Hopefully you got everything working well using the Image component of choice. I'll close the issue, but feel free to create a new one in case you encounter any issues.
