### ISSUE TITLE
Cache directories not cleaned up

### ISSUE THREAD

**Issue by aeirola** [aeirola/react-native-svg-asset-plugin#4]
The plugin caches generated PNG images under `.png-cache` directories adjacent to any imported SVG files. Due to metro bundler caching, the plugin retains all old versions of SVG images in the caches, meaning that the caches only grow as more changes are made to the SVG files. This can cause unnecessary disk space usage.

**Comment by aeirola** [comment]
This could be mitigated by a separate PNG cache cleanup script which the users could run on project cleanup.

**Comment by aeirola** [comment]
Alternatively, the plugin could try to identify old image caches on subsequent runs, and remove any images which seem old, and have a later version available. This would be more automatic, but might still cause issues metro caching. Would need to check if the metro cache has any expiry dates.

**Comment by kashishgrover** [comment]
@aeirola Thanks for this plugin. It is really great!
With respect to this issue, why don't you overwrite files based on the SVG filenames? Don't you think that will resolve this issue?

**Comment by aeirola** [comment]
That is a valid idea. Unfortunately we need to retain old versions of images due to the way the metro bundler caching works. The metro bundler calls the asset plugins only once for each version of a file, and caches the results based on file hashes. Thus the old versions need to be kept on disk so that the metro bundler can provide the images for previously cached results as well.

**Comment by aeirola** [comment]
Been thinking about this, and decided that the best way would be to identify scenarios where the asset plugin is called by metro for files which have already been rendered as PNGs. In this case we can assume that the metro cache doesn't contain the file anymore, nor any earlier versions of the file. Thus we should be able to safely remove all PNGs generated before the creation date of the file being re-generated as a PNG.

Related to this, I think there are some possible optimisations in not re-rendering existing files every time metro calls the plugin. The cached PNGs persist even though metro cache is cleared, thus we could save some resources by reusing the existing PNGs. Would of course need to take into account changed configs and plugin versions, but this shouldn't require more than just a fs modified timestamp check.

I'll try to implement this logic once I find some time for the project.
