### ISSUE TITLE
Feature request: configure ignore folder

### ISSUE THREAD

**Issue by papigers** [aeirola/react-native-svg-asset-plugin#40]
Looking at the current configuration opens it's not possible to configure a folder from which all required SVG files will be ignored. This prevents me from using this plugin in conjunction with `react-native-svg`.

Is there maybe any way to achieve this using metro configuration alone?
Thanks.

**Comment by aeirola** [comment]
Doesn't look like metro would support configuring asset plugins for specific paths only, so this would be something that would need to be implemented in each asset plugin.

Interesting to hear that you would want to use the plugin alongside react-native-svg. What is the use case where you prefer to include larger prerendered PNG files over smaller SVG files when you already pay for the overhead of including an SVG renderer in the application bundle?

Nonetheless, this is something which could well be supported by this library. What kind of configuration structure do you think would be most useful? A regexp string for ignored paths? The same, but for whitelisting? Something else?

**Comment by papigers** [comment]
I'd like to use this plugin for svg files that are used as actual images (for instance, a shadow shape that spans the whole screen as a backround image). On the contrary, for icons (I have a lot of original svg icons made by the design team), I'd like to use `react-native-svg`.
Maybe I'm overthinking it, but as much as this plugin is very useful it also should be used carefully in order to avoid huge bundle sizes.

Is that makes sense?

For my use case it's only a subfolder that should be ignored, but I guess it better to have it configurable with a regex pattern matching the full path of the file.

**Comment by aeirola** [comment]
Ah, so you are prerendering larger / more complex images in order to avoid a performance hit or delays from on-the-fly rendering. That makes sense.

If you want, you could make a PR for the feature. Otherwise I'll probably take a look at it over the weekend.

**Comment by papigers** [comment]
Cool, I'll give it a go tomorrow :)

**Comment by papigers** [comment]
I ended up using glob patterns using `ignore`, guessed it could give a better developer experience, similar to using .gitignore.
Hope that's ok.

**Comment by aeirola** [comment]
Support for ignores was released in version 0.4.0
